#version 460
#extension GL_EXT_shader_image_load_formatted : require

layout(binding = 0) uniform image2D _RenderTarget;
layout(binding = 1) uniform image2D _PostProcessTarget;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() {
  uvec2 index = gl_GlobalInvocationID.xy;
  uvec2 dims = uvec2(imageSize(_RenderTarget));
  if (!all(lessThan(index, dims))) return;
  imageStore(_RenderTarget, ivec2(index), imageLoad(_PostProcessTarget, ivec2(index)));
}